/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Usuario;
import Listas.SG;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author devcast
 */
public class ListadoUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form ListadoUsuarios
     */
    public ListadoUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Genero", "Contrasñea", "Accion"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        
        
      DefaultTableModel model = new DefaultTableModel();

    // Agregar columnas al modelo
    model.addColumn("Codigo");
    model.addColumn("Nombre");
    model.addColumn("Genero");
    model.addColumn("Contrasñea");
    model.addColumn("Accion");

        
    // Agregar filas al modelo
    
    int cantidadUsuarios = Listas.SG.listadoUsuarios.getCantidad();
   
        for (int i = 0; i < cantidadUsuarios; i++) {
            Usuario usuarioObtenido = Listas.SG.listadoUsuarios.getUsuarioIndice(i);
            
            model.addRow(new Object[]{usuarioObtenido.getCodigo(), usuarioObtenido.getNombre(), usuarioObtenido.getGenero(), usuarioObtenido.getContraseña(), "ver"});
                       
        }
    
    
    
    

    // Asignar el modelo a la tabla
    tableData.setModel(model);

    // Agregar un MouseListener a la tabla
    tableData.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            System.out.println("Click");
            int fila = tableData.rowAtPoint(e.getPoint());
            int columna = tableData.columnAtPoint(e.getPoint());

            if (columna == 4) { // Columna 4 es la columna "Accion"
                String codigo = tableData.getValueAt(fila, 0).toString();
                String nombre = tableData.getValueAt(fila, 1).toString();
                String genero = tableData.getValueAt(fila, 2).toString();
                String contrasena = tableData.getValueAt(fila, 3).toString();

                System.out.println("Codigo: " + codigo + " Nombre: " + nombre);

                // Generar el archivo HTML
                try (FileWriter fileWriter = new FileWriter("output.html")) {
                    fileWriter.write("<html>\n");
                    fileWriter.write("<head><title>Detalles de Usuario</title></head>\n");
                    fileWriter.write("<body>\n");
                    fileWriter.write("<h1>Detalles de Usuario</h1>\n");
                    fileWriter.write("<p><strong>Codigo:</strong> " + codigo + "</p>\n");
                    fileWriter.write("<p><strong>Nombre:</strong> " + nombre + "</p>\n");
                    fileWriter.write("<p><strong>Genero:</strong> " + genero + "</p>\n");
                    fileWriter.write("<p><strong>Contraseña:</strong> " + contrasena + "</p>\n");
                    fileWriter.write("</body>\n");
                    fileWriter.write("</html>\n");
                } catch (IOException ex) {
                    ex.printStackTrace();
                }

                System.out.println("Archivo HTML generado con éxito.");
            }
        }
    });
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    // End of variables declaration//GEN-END:variables
}
